In [7]:
# Auto Gradient 자동 미분 행렬 기초
# Pytorch 모든 신경망 중심에는 AutoGrad 패키지가 있음
# 이를 활용하여 해당 신경망을 학습 및 처리 가능함
import torch
x = torch.ones(2,2,requires_grad=True)
print(x)
# 텐서의 연산결과로 나온 (여기서 2는 2차원 벡터임) 행렬은 grad_fn 을 가짐
y = x + 2
print(y)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [18]:
z = y * y * 3
# 여기서 mean() Function은 모든 행렬의 요소성분의 평균을 의미함
out = z.mean()

print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [19]:
a = torch.randn(2,2)
print(a)
a = ((a*3) / (a-1))
print(a)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)
print(a)
print(b)

tensor([[ 0.5081,  0.6978],
        [-1.6451,  0.7139]])
tensor([[-3.0983, -6.9287],
        [ 1.8658, -7.4841]])
False
True
tensor([[-3.0983, -6.9287],
        [ 1.8658, -7.4841]], requires_grad=True)
tensor(117.0992, grad_fn=<SumBackward0>)


In [20]:
out.backward()
print(x.grad)

tensor([[9., 9.],
        [9., 9.]])
