In [1]:
from __future__ import print_function

In [2]:
import torch

In [4]:
x = torch.empty(5,3)
print(x)

tensor([[2.9316e-06, 4.5818e-41, 2.9316e-06],
        [4.5818e-41, 2.1122e+20, 1.0812e-05],
        [4.2882e-08, 6.6291e-10, 5.4455e-05],
        [1.6613e-07, 4.1577e+21, 2.0942e+23],
        [2.3049e-12, 7.1429e+31, 2.5226e-18]])


In [6]:
x = torch.rand(5,3)
print(x)

tensor([[0.0467, 0.5102, 0.9600],
        [0.4626, 0.4864, 0.3084],
        [0.9663, 0.1441, 0.9563],
        [0.4059, 0.3462, 0.3151],
        [0.6634, 0.2860, 0.4012]])


In [7]:
x = torch.zeros(5,3,dtype=torch.long)
x = print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

x = torch.rand_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.6054, 0.4572, 0.1337],
        [0.3835, 0.1276, 0.9844],
        [0.0400, 0.2139, 0.4739],
        [0.2975, 0.0048, 0.5554],
        [0.4550, 0.5097, 0.1705]])


In [10]:
#x.size() - 행렬의 크기
print(x.size())

torch.Size([5, 3])


In [13]:
#행렬 간 덧셈 수행
y = torch.rand(5,3)
print(x+y)

tensor([[1.1300, 1.1967, 0.8436],
        [0.5035, 1.0709, 1.1360],
        [0.5302, 0.3745, 0.6240],
        [0.7057, 0.1845, 1.4483],
        [0.7806, 1.2706, 0.1877]])


In [16]:
result = torch.empty(5,3)
#비어있지만 무수히 작은 입실론이 존재함.
print(result)
torch.add(x,y,out=result)
print(result)

tensor([[8.2016e-23, 3.0967e-41, 8.1002e-23],
        [3.0967e-41, 1.1210e-43, 0.0000e+00],
        [8.9683e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [2.6677e-23, 0.0000e+00, 0.0000e+00]])
tensor([[1.1300, 1.1967, 0.8436],
        [0.5035, 1.0709, 1.1360],
        [0.5302, 0.3745, 0.6240],
        [0.7057, 0.1845, 1.4483],
        [0.7806, 1.2706, 0.1877]])


In [ ]:
y.add_(x)