In [3]:
from __future__ import print_function

In [4]:
import torch

In [5]:
x = torch.empty(5,3)
print(x)

tensor([[-1.3984e+02,  4.5566e-41, -3.9100e+02],
        [ 4.5566e-41, -4.0833e+02,  4.5566e-41],
        [-3.8925e+02,  4.5566e-41,  1.9541e-27],
        [ 4.5566e-41,  1.9586e-27,  4.5566e-41],
        [ 1.9586e-27,  4.5566e-41, -2.3563e+02]])


In [6]:
x = torch.rand(5,3)
print(x)

tensor([[0.1909, 0.5438, 0.4258],
        [0.9446, 0.8444, 0.6490],
        [0.3542, 0.8846, 0.8612],
        [0.6323, 0.4594, 0.7666],
        [0.3641, 0.9366, 0.2692]])


In [7]:
x = torch.zeros(5,3,dtype=torch.long)
x = print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

x = torch.rand_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.5196, 0.2571, 0.7783],
        [0.2053, 0.1328, 0.2940],
        [0.3947, 0.3170, 0.9306],
        [0.2074, 0.8880, 0.4708],
        [0.0809, 0.2792, 0.8710]])


In [10]:
#x.size() - 행렬의 크기
print(x.size())

torch.Size([5, 3])


In [11]:
#행렬 간 덧셈 수행
y = torch.rand(5,3)
print(x+y)

tensor([[0.7366, 1.1990, 1.3885],
        [0.4016, 0.3924, 0.9778],
        [1.0763, 0.6992, 1.8626],
        [0.5246, 1.0588, 0.6808],
        [0.3128, 0.7391, 1.7447]])


In [12]:
result = torch.empty(5,3)
#비어있지만 무수히 작은 입실론이 존재함.
print(result)
torch.add(x,y,out=result)
print(result)

tensor([[-9.8170e+02,  4.5566e-41, -1.3840e-29],
        [ 3.0871e-41,  4.4842e-44,  0.0000e+00],
        [ 8.9683e-44,  0.0000e+00, -1.3910e-29],
        [ 3.0871e-41,  0.0000e+00,  0.0000e+00],
        [ 4.4842e-44,  0.0000e+00,  1.1210e-43]])
tensor([[0.7366, 1.1990, 1.3885],
        [0.4016, 0.3924, 0.9778],
        [1.0763, 0.6992, 1.8626],
        [0.5246, 1.0588, 0.6808],
        [0.3128, 0.7391, 1.7447]])


In [19]:
# torch.add(x,y,out=result) = y.add_(x) 와 동일
# 행렬 바꾸기 방식은 _ 가 붙어서 진행
y.add_(x)
print(y)
# Numpy 방식
print(y[:,0]) # 1열을 출력
print(y[:,1]) # 2열을 출력
print(y[:,2]) # 3열을 출력
print(y[0,:]) # 1행을 출력

tensor([[3.8541, 2.7415, 6.0581],
        [1.6337, 1.1894, 2.7416],
        [3.4446, 2.6009, 7.4463],
        [1.7690, 6.3868, 3.5055],
        [0.7980, 2.4140, 6.9709]])
tensor([3.8541, 1.6337, 3.4446, 1.7690, 0.7980])
tensor([2.7415, 1.1894, 2.6009, 6.3868, 2.4140])
tensor([6.0581, 2.7416, 7.4463, 3.5055, 6.9709])
tensor([3.8541, 2.7415, 6.0581])


In [22]:
#행렬의 크기 나 모양을 변경하고 싶다면
x = torch.rand(4,4) # 4X4 행렬
y = x.view(16)  # 16X1 행렬
z = x.view(-1,8) # 2X8 행렬
print(y)
print(z)
print(x.size(),y.size(),z.size())

tensor([0.8663, 0.3601, 0.4625, 0.6606, 0.3806, 0.9869, 0.3168, 0.3501, 0.3894,
        0.7620, 0.6783, 0.8569, 0.6023, 0.0619, 0.6463, 0.4132])
tensor([[0.8663, 0.3601, 0.4625, 0.6606, 0.3806, 0.9869, 0.3168, 0.3501],
        [0.3894, 0.7620, 0.6783, 0.8569, 0.6023, 0.0619, 0.6463, 0.4132]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [24]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.1203])
-1.120332956314087


In [29]:
# 1 X 5 의 E 행렬 생성
a = torch.ones(5)
print(a)
b = torch.ones(10)
print(b)

a.add_(1)
print(a)
b.add_(3)
print(b)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([2., 2., 2., 2., 2.])
tensor([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])


In [31]:
# Tensor 와 Numpy 로 형성된 Array 행렬은 서로 상호 치환 가능하다.
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)
b.add_(4)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
tensor([6., 6., 6., 6., 6.], dtype=torch.float64)
